"
Comentario.
"
Class {
	#name : #ClaseNueva,
	#superclass : #Object,
	#instVars : [
		'var1',
		'var2',
		'var3'
	],
	#category : #NuevoPaquete
}

{ #category : #accessing }
ClaseNueva >> var1 [

	^ var1
]

{ #category : #accessing }
ClaseNueva >> var1: anObject [

	var1 := anObject
]

{ #category : #accessing }
ClaseNueva >> var2 [

	^ var2
]

{ #category : #accessing }
ClaseNueva >> var2: anObject [

	var2 := anObject
]

{ #category : #accessing }
ClaseNueva >> var3 [

	^ var3
]

{ #category : #accessing }
ClaseNueva >> var3: anObject [

	var3 := anObject
]
