"
Este es un comentario
"
Class {
	#name : #ClaseN4,
	#superclass : #Object,
	#instVars : [
		'un',
		'dos',
		'tres',
		'cuatro'
	],
	#category : #PaqueteN4
}

{ #category : #accessing }
ClaseN4 >> cuatro [

	^ cuatro
]

{ #category : #accessing }
ClaseN4 >> cuatro: anObject [

	cuatro := anObject
]

{ #category : #accessing }
ClaseN4 >> dos [

	^ dos
]

{ #category : #accessing }
ClaseN4 >> dos: anObject [

	dos := anObject
]

{ #category : #accessing }
ClaseN4 >> tres [

	^ tres
]

{ #category : #accessing }
ClaseN4 >> tres: anObject [

	tres := anObject
]

{ #category : #accessing }
ClaseN4 >> un [

	^ un
]

{ #category : #accessing }
ClaseN4 >> un: anObject [

	un := anObject
]
