Class {
	#name : #ClaseP1,
	#superclass : #Object,
	#instVars : [
		'nombre',
		'cantidad'
	],
	#category : #PaquetePrueba
}

{ #category : #accessing }
ClaseP1 >> cantidad [

	^ cantidad
]

{ #category : #accessing }
ClaseP1 >> cantidad: anObject [

	cantidad := anObject
]

{ #category : #accessing }
ClaseP1 >> nombre [

	^ nombre
]

{ #category : #accessing }
ClaseP1 >> nombre: anObject [

	nombre := anObject
]
